apiVersion: v1
kind: Secret
metadata:
  name: django-superuser-secret
type: Opaque
stringData:
  DJANGO_SUPERUSER_EMAIL: 'olberd@bk.ru'
  DJANGO_SUPERUSER_USERNAME: 'olberd'
  DJANGO_SUPERUSER_PASSWORD: 'oldik1970'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: createsuperuser
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: django-app
          image: olberd/django-hub:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
          envFrom:
            - secretRef:
                name: django-secret
            - secretRef:
                name: django-superuser-secret
          command: [ 'python', 'manage.py', 'createsuperuser', '--noinput' ]