apiVersion: v1
kind: Secret
metadata:
  name: django-superuser-secret
type: Opaque
stringData:
  DJANGO_SUPERUSER_EMAIL: <base64-encoded-email>
  DJANGO_SUPERUSER_USERNAME: <base64-encoded-username>
  DJANGO_SUPERUSER_PASSWORD: <base64-encoded-pass>