apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions-cron-job
  labels:
    app: django
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: clearsessions-cron-job
              image: olberd/django-hub
              imagePullPolicy: IfNotPresent
              command: [ "python", "manage.py", "clearsessions" ]
          restartPolicy: Never