apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-admin
  labels:
    name: django-admin
spec:
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: olberd/django-hub
          ports:
            - containerPort: 80