apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-admin
  labels:
    name: django-admin
spec:
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: olberd/django-hub
          ports:
            - containerPort: 80
          env:
            - name: DEBUG
              value: "True"


---
apiVersion: v1
kind: Service
metadata:
  name: django-admin-service
  labels:
    env: prod
    owner: olberd
spec:
  selector:
    app: django-app
  ports:
    - name: django-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
