apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    app: django
spec:
  template:
    spec:
      containers:
        - name: django-migrate
          image: olberd/django-hub
          imagePullPolicy: IfNotPresent
          command: [ "python", "manage.py", "migrate", "--noinput" ]
      restartPolicy: Never